main: net.tfminecraft.AdvancedCrafting.AdvancedCrafting
api-version: 1.20
name: AdvancedCrafting
version: 1.0
author: Drefvelin

depend: [TLibs, MMOCore, MMOItems, MythicLib]

commands:
  advancedcrafting:
    useage: /<command>
    description: AdvancedCrafting Command